# Calamares Konfigurationsdatei für ducklingOS
modules-search: [ $(qtpaths --plugin-dir 2>/dev/null || echo /usr/lib/qt/plugins), /usr/lib/calamares/modules ]

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpack
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - grubcfg
      - bootloader
      - branding
      - remove
  - show:
      - finished

internetCheckUrl: "http://detectportal.firefox.com/success.txt"

branding: default
prompt-install: false
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
